trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    mkdir -p './dags ./logs ./plugins ./config'
  displayName: 'Create directories'

- script: |
    echo -e "AIRFLOW_UID=$(id -u)" > .env
    export AIRFLOW_UID=50000
  displayName: 'Set environment variables'
  
  
- task: AzureCLI@2
  displayName: 'Deploy containers to ACI'
  inputs:
    azureSubscription: 'ContainerInstancesSC'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az container create --resource-group dev-ingestion-framework --file docker-compose.yaml --name airflow docker-compose.yaml --registry-login-server devingest.azurecr.io --registry-username devingest --registry-password $(ACR_PASS)
#      az container create --resource-group dev-ingestion-framework --file docker-compose.yaml --name airflow --dns-name-label your-dns-name --location your-location
