# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main  # Trigger the pipeline on commits to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use Ubuntu as the agent image

stages:
- stage: DeployContainers
  displayName: 'Deploy Containers'
  jobs:
  - job: DeployUsingDockerCompose
    displayName: 'Deploy using Docker Compose'
    steps:
    - task: Docker@2
      displayName: 'Login to Azure Container Registry'
      inputs:
        command: 'login'
        containerRegistry: 'ContainerRegistrySC'
    - script: |
        docker-compose -f $(Build.SourcesDirectory)/docker-compose.yaml pull
        docker-compose -f $(Build.SourcesDirectory)/docker-compose.yaml up -d
      displayName: 'Pull and Run Docker Compose'
    - task: AzureCLI@2
      displayName: 'Deploy to Azure Container Instances'
      inputs:
        azureSubscription: 'ContainerInstancesSC'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Create Azure Container Instances based on the Docker images
          az container create --name airflow-container --image devingest.azurecr.io/airflow:2.6.1 --resource-group dev-ingestion-framework --restart-policy Always --ports 80
          az container create --name redis-container --image devingest.azurecr.io/redis:latest --resource-group dev-ingestion-framework --restart-policy Always
          az container create --name statsd-exporter-container --image devingest.azurecr.io/statsd-exporter:v0.24.0 --resource-group dev-ingestion-framework --restart-policy Always --ports 9102 9125
          az container create --name prometheus-container --image devingest.azurecr.io/prometheus:v2.37.9 --resource-group dev-ingestion-framework --restart-policy Always --ports 9090
          az container create --name grafana-container --image devingest.azurecr.io/grafana:10.0.3-ubuntu --resource-group dev-ingestion-framework --restart-policy Always --ports 3000
