trigger:
- main

pool:
  name: 'default'

stages:
- stage: DeployContainers
  displayName: 'Deploy Containers'
  jobs:
  - job: DeployUsingDockerCompose
    displayName: 'Deploy using Docker Compose'
    steps:
    
    - task: Docker@2
      displayName: 'Login to Azure Container Registry'
      inputs:
        command: 'login'
        containerRegistry: 'ContainerRegistrySC'

   # - script: |
   #     mkdir /opt/airflow
   #     cd /opt/airflow
   #     mkdir -p './dags ./logs ./plugins ./config'
   #   displayName: 'Create directories'

    - script: |
        echo -e "AIRFLOW_UID=$(id -u)" > .env
        export AIRFLOW_UID=50000
      displayName: 'Set environment variables'

    - script: |
        docker-compose up airflow-init
        docker-compose up -d
      displayName: 'Deploy Airflow'    
